image: node:16
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run docs:build
  after_script:
    - mkdir public
    - cp -r .vitepress/dist/* public

  artifacts:
    paths:
      - public
  only:
    - main